---
title: "Get AGES cases Altersgruppen"
author: "Erich Neuwirth"
date: "7/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
keep_download_data <- FALSE
```

```{r}
suppressPackageStartupMessages({
  library(here)
  library(tidyverse)
  library(fs)
  library(purrr)
})
```


```{r ems03}
suppressMessages(
  source(file.path(
    here(), "utils",
    "purl_and_source.R"
  ))
)
```


```{r ems04}
suppressMessages(
  purl_and_source(file.path(
    here(), "utils",
    "utils.Rmd"
  ))
)
```

```{r}
coronaDAT_url <- "https://github.com/statistikat/coronaDAT"
```


```{r}
if (!dir_exists(file.path(
  here(), "data", "downloaded",
  "coronaDAT"
))) {
  setwd(file.path(here(), "data", "downloaded"))
  system("git clone https://github.com/statistikat/coronaDAT")
} else {
  setwd(file.path(here(), "data", "downloaded", "coronaDAT"))
  system("git pull")
}
setwd(here())
```
```{r}
coronaDAT_dir <- file.path(
  here(), "data", "downloaded",
  "coronaDAT", "archive"
)
```

```{r alter4}
dir_ls(coronaDAT_dir) ->
alter_dirs
```


```{r alter6, warning=FALSE}
dates <- c()
suppressWarnings({
  for (d in alter_dirs) {
    zip_file <-
      dir_ls(file.path(d, "data"))


    if (str_detect(zip_file, "_orig_csv_ages.zip$")) {
      str_split(zip_file, "/") |>
        unlist() |>
        (\(x)x[10])() ->
      file_date
      dates <- c(dates, file_date)
    }
  }
  dates |>
    keep(\(x)!str_detect(x, "[[:letter:]]")) |>
    keep(~ as.numeric(.) > 20210525) ->
  date_strings_to_use
})
```


```{r alter7}
altersgruppen_since_may26 <- tibble()
for (dir_mid in date_strings_to_use) {
  d <- paste(coronaDAT_dir, dir_mid, "data", sep = "/")
  file_to_unzip <- dir_ls(d)
  Datum <- paste(str_sub(dir_mid, 1, 4),
    str_sub(dir_mid, 5, 6),
    str_sub(dir_mid, 7, 8),
    sep = "-"
  ) |> as.Date()
  if ((file_to_unzip |> length()) > 1) {
    file_to_unzip <- (file_to_unzip |> first())
  }
  ex_dir <- file.path(here(), "unzipped")
  if (dir_exists(ex_dir)) {
    dir_delete(ex_dir)
  }
  unzip(file_to_unzip,
    files = "CovidFaelle_Altersgruppe.csv",
    exdir = ex_dir
  )

  one_day_df <-
    suppressMessages(
      read_csv2(file.path(
        file.path(
          here(), "unzipped",
          "CovidFaelle_Altersgruppe.csv"
        )
      ))
    ) |>
    mutate(Datum = Datum) |>
    select(Datum, everything())

  altersgruppen_since_may26 |>
    bind_rows(one_day_df) ->
  altersgruppen_since_may26
}

altersgruppen_since_may26 |>
  mutate(Altersgruppe = case_when(
    Altersgruppe == "<5" ~ "0-4",
    Altersgruppe == ">84" ~ "85-",
    TRUE ~ Altersgruppe
  )) ->
altersgruppen_since_may26
```

```{r}
load(file.path(
  here(), "data_base",
  "altersgruppen_df_upto_20210525.RData"
))
```

```{r}
bind_rows(
  altersgruppen_df_upto_20210525,
  altersgruppen_since_may26
) |>
  rename(pop_AGES=AnzEinwohner) |>
  rename(cases_AGES=Anzahl) |>
  rename(Genesen_AGES=AnzahlGeheilt) |>
  rename(Tot_AGES=AnzahlTot) ->
cases_ages_alter
```


```{r}
cases_ages_alter |>
  pull(Datum) |>
  unique() |>
  sort() ->
  dates_available
dates_all <-
  seq(min(dates_available),max(dates_available),by="1 day")
dates_missing <-
  setdiff(dates_all,dates_available)
# dates_missing 
```




```{r}
create_dir_if_needed(file.path(here(), 
                               "data", "rdata_preliminary"))
```

```{r}
save(cases_age_ages,
  file = file.path(
    here(), "data", "rdata_preliminary",
    "cases_ages_alter.RData"
  )
)
```

